# Generated by Django 4.2.7 on 2023-11-23 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_b_cnic_feetype_teacher_feepayment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="b_cnic",
            options={"verbose_name_plural": "b_cnic"},
        ),
        migrations.AlterField(
            model_name="student",
            name="student_regis",
            field=models.IntegerField(null=True),
        ),
    ]
