# Generated by Django 4.2.7 on 2023-11-13 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_remove_student_admin_student_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="f_mobile",
            field=models.TextField(default="", max_length=11),
        ),
        migrations.AddField(
            model_name="student",
            name="f_name",
            field=models.TextField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="student",
            name="f_oc",
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="m_mobile",
            field=models.TextField(default="", max_length=11, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="m_name",
            field=models.TextField(default=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="m_oc",
            field=models.TextField(default="", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="address",
            field=models.TextField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="student",
            name="dob",
            field=models.DateField(default=""),
        ),
        migrations.AlterField(
            model_name="student",
            name="first_name",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="student",
            name="last_name",
            field=models.CharField(default="", max_length=200),
        ),
    ]
