# Generated by Django 4.2.7 on 2023-11-13 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_student_f_mobile_student_f_name_student_f_oc_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="f_mobile",
            new_name="father_mobile",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="f_name",
            new_name="father_name",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="f_oc",
            new_name="father_oc",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="m_mobile",
            new_name="mother_mobile",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="m_name",
            new_name="mother_name",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="m_oc",
            new_name="mother_oc",
        ),
        migrations.AddField(
            model_name="student",
            name="student_pic",
            field=models.ImageField(
                default="", null=True, upload_to="media/student_pic"
            ),
        ),
    ]
