# Generated by Django 4.2.7 on 2023-11-23 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_remove_feepayment_b_cnic_delete_feetype_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="student_regis",
            field=models.CharField(max_length=500, null=True),
        ),
    ]
