# Generated by Django 4.2.7 on 2023-11-13 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_rename_f_mobile_student_father_mobile_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="b_cnic",
            field=models.CharField(max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="father_oc",
            field=models.TextField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="student",
            name="first_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="student",
            name="last_name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="mother_mobile",
            field=models.TextField(blank=True, default="", max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="mother_name",
            field=models.TextField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="mother_oc",
            field=models.TextField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="student_pic",
            field=models.ImageField(
                blank=True, default="", null=True, upload_to="media/student_pic"
            ),
        ),
    ]
