# Generated by Django 4.2.7 on 2023-11-17 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_alter_student_b_cnic_alter_student_father_oc_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="section_abc",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
