# Generated by Django 4.2.7 on 2023-11-23 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_b_cnic_feetype_section_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="section_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="app.section"
            ),
        ),
    ]
